AWSTemplateFormatVersion: '2010-09-09'

Description: TfL Real Time Monitoring Pipeline

Resources:

  BronzeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "tfl-bronze-${AWS::AccountId}"

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TflLambdaRole

      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:

              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: "*"

              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: "*"

  TflLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TflArrivalIngestion

      Runtime: python3.12

      Handler: tfl_ingestion.lambda_handler

      Timeout: 60

      Role: !GetAtt LambdaRole.Arn

      Code:
        S3Bucket: tfl-deployment-artifacts-maha1
        S3Key: lambda.zip

      Environment:
        Variables:
          BUCKET_NAME: !Ref BronzeBucket

  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: TflEvery5Minutes

      ScheduleExpression: rate(5 minutes)

      State: ENABLED

      Targets:
        - Arn: !GetAtt TflLambda.Arn
          Id: LambdaTarget

  EventBridgePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TflLambda
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventBridgeRule.Arn

Outputs:

  BronzeBucketName:
    Description: Bronze S3 Bucket
    Value: !Ref BronzeBucket

  LambdaFunctionName:
    Description: Lambda Function Name
    Value: !Ref TflLambda

  EventBridgeRuleName:
    Description: EventBridge Rule Name
    Value: !Ref EventBridgeRule
